sonar.projectKey=demo-app
sonar.projectName=Demo App
sonar.sources=app/src/main
sonar.tests=app/src/test
sonar.java.binaries=app/target/classes
sonar.coverage.jacoco.xmlReportPaths=app/target/site/jacoco/jacoco.xml
